<?php
use think\facade\Route;

Route::pattern([
    'name' => '\w+',
]);

Route::get('/', 'index/index/index');
Route::get('login', 'login/index/index');
Route::get('register', 'register/index/index');
Route::get('page/netease', 'api/Page/netease');
Route::get('page/autograph', 'api/Page/autograph');
Route::get('page/love', 'api/Page/love');
Route::get('page/name', 'api/Page/name');
Route::get('page/shuoshuo', 'api/Page/shuoshuo');
Route::get('page/word', 'api/Page/word');
Route::get('page/log', 'api/Page/log');
Route::get('page/likes', 'api/Page/likes');
Route::get('page/headimg', 'api/Page/headimg');
Route::get('skey', 'api/Skey/index');
Route::get('update/music_hot', 'api/Update/Music_hot');
Route::get('update/word', 'api/Update/Word');
Route::get('update/wordtime', 'api/Update/Wordtime');
Route::get('update/netease', 'api/Update/netease');
Route::get('update/headimg', 'api/Update/headimg');
Route::get('update/words', 'api/Update/words');
Route::get('update/qianming', 'api/Update/qianming');
Route::get('update/wangming', 'api/Update/wangming');
Route::get('update/net', 'api/Update/net');
Route::get('update/dog', 'api/Update/dog');
Route::rule('v2/userinfo', 'api/V2/UserInfo', 'GET|POST');
Route::rule('v2/url', 'api/V2/Url', 'GET|POST');
Route::rule('v2/qlogo', 'api/V2/qlogo', 'GET|POST');
Route::rule('v2/gravatar', 'api/V2/Gravatar', 'GET|POST');
Route::rule('v2/bing_img', 'api/V2/Bing_img', 'GET|POST');
Route::rule('v2/image', 'api/V2/image', 'GET|POST');
Route::rule('v2/ip', 'api/V2/IP', 'GET|POST');
Route::rule('v2/ip_img', 'api/V2/IP_IMG', 'GET|POST');
Route::rule('v2/email', 'api/V2/Email', 'GET|POST');
Route::rule('v2/icp', 'api/V2/ICP', 'GET|POST');
Route::rule('v2/dm_img', 'api/V2/DM_IMG', 'GET|POST');
Route::rule('v2/c_img', 'api/V2/C_IMG', 'GET|POST');
Route::rule('v2/netease', 'api/V2/netease', 'GET|POST');
Route::rule('v2/love', 'api/V2/love', 'GET|POST');
Route::rule('v2/name', 'api/V2/Name', 'GET|POST');
Route::rule('v2/autograph', 'api/V2/autograph', 'GET|POST');
Route::rule('v2/shuoshuo', 'api/V2/shuoshuo', 'GET|POST');
Route::rule('v2/word', 'api/V2/word', 'GET|POST');
Route::rule('v2/music_163', 'api/V2/Music_163', 'GET|POST');
Route::rule('v2/music', 'api/V2/Music', 'GET|POST');
Route::rule('v2/music_hot', 'api/V2/Music_hot', 'GET|POST');
Route::rule('v2/md5', 'api/V2/MD5', 'GET|POST');
Route::rule('v2/qrcode', 'api/V2/QrCode', 'GET|POST');
Route::rule('v2/qrreader', 'api/V2/QrReader', 'GET|POST');
Route::rule('v2/mobile', 'api/V2/Mobile', 'GET|POST');
Route::rule('v2/whois', 'api/V2/whois', 'GET|POST');
Route::rule('v2/pinyin', 'api/V2/pinyin', 'GET|POST');
Route::rule('v2/fanyi', 'api/V2/fanyi', 'GET|POST');
Route::rule('v2/ping', 'api/V2/ping', 'GET|POST');
Route::rule('v2/robot', 'api/V2/robot', 'GET|POST');
Route::rule('v2/weather', 'api/V2/weather', 'GET|POST');
Route::rule('v2/laji', 'api/V2/laji', 'GET|POST');
Route::rule('v2/address', 'api/V2/address', 'GET|POST');
Route::rule('v2/check', 'api/V2/check', 'GET|POST');
Route::rule('v2/check_domain', 'api/V2/check_domain', 'GET|POST');
Route::rule('v2/du_word', 'api/V2/du_word', 'GET|POST');
Route::rule('v2/url_sec', 'api/V2/Url_Sec', 'GET|POST');
Route::rule('v2/baidu_upload', 'api/V2/Baidu_Upload', 'GET|POST');
Route::rule('v2/sogou_upload', 'api/V2/Sogou_Upload', 'GET|POST');
Route::rule('v2/upload', 'api/V2/upload', 'GET|POST');
Route::rule('v2/proxy', 'api/V2/proxy', 'GET|POST');
Route::rule('v2/headimg', 'api/V2/HeadImg', 'GET|POST');
Route::rule('v2/today', 'api/V2/today', 'GET|POST');
Route::rule('v2/audio', 'api/V2/audio', 'GET|POST');
Route::rule('v2/colors', 'api/V2/colors', 'GET|POST');
Route::rule('v2/qunlogo', 'api/V2/qunlogo', 'GET|POST');
Route::rule('v2/chengyu', 'api/V2/chengyu', 'GET|POST');
Route::rule('v2/xiaohua', 'api/V2/xiaohua', 'GET|POST');
Route::rule('v2/httpcode', 'api/V2/HttpCode', 'GET|POST');
Route::rule('v2/randpass', 'api/V2/RandPass', 'GET|POST');
Route::rule('v2/go', 'api/V2/Go', 'GET|POST');
Route::rule('v2/music_list_163', 'api/V2/Music_List_163', 'GET|POST');
Route::rule('v2/district', 'api/V2/district', 'GET|POST');
Route::rule('v2/weatherinfo', 'api/V2/WeatherInfo', 'GET|POST');
Route::rule('v2/ipsadd', 'api/V2/IpSadd', 'GET|POST');
Route::rule('v2/kugou', 'api/V2/Kugou', 'GET|POST');
Route::rule('v2/qq', 'api/V2/qq', 'GET|POST');
Route::rule('v2/kuwo', 'api/V2/kuwo', 'GET|POST');
Route::rule('v2/xiami', 'api/V2/xiami', 'GET|POST');
Route::rule('v2/migu', 'api/V2/migu', 'GET|POST');
Route::rule('v2/kg', 'api/V2/kg', 'GET|POST');
Route::rule('v2/musicurl', 'api/V2/MusicUrl', 'GET|POST');
Route::rule('v2/qqchat', 'api/V2/QQChat', 'GET|POST');
Route::rule('v2/qqinfo', 'api/V2/QQInfo', 'GET|POST');
Route::rule('v2/douyin', 'api/V2/douyin', 'GET|POST');
Route::rule('v2/qqxj', 'api/V2/qqxj', 'GET|POST');
Route::rule('v2/telxj', 'api/V2/telxj', 'GET|POST');
Route::rule('v2/idcard', 'api/V2/idcard', 'GET|POST');
Route::rule('v2/dog', 'api/V2/dog', 'GET|POST');
Route::rule('v2/kuaishou', 'api/V2/kuaishou', 'GET|POST');
Route::rule('v2/weishi', 'api/V2/weishi', 'GET|POST');
Route::rule('v2/pipixia', 'api/V2/pipixia', 'GET|POST');
Route::rule('v2/miaopai', 'api/V2/miaopai', 'GET|POST');
Route::get('hello/:id', 'index/hello')->pattern(['id' => '\d+']);
Route::post('hello/:name', 'index/hello');
