<?php
include('config.php');
//获取顶级域名
function get_host(){
  $url   = $_SERVER['HTTP_HOST'];
  $data = explode('.', $url);
  $co_ta = count($data);
  //判断是否是双后缀
  $zi_tow = true;
  $host_cn = 'com.cn,net.cn,org.cn,gov.cn';
  $host_cn = explode(',', $host_cn);
  foreach($host_cn as $host){
    if(strpos($url,$host)){
      $zi_tow = false;
    }
  }
  //如果是返回FALSE ，如果不是返回true
  if($zi_tow == true){
    $host = $data[$co_ta-2].'.'.$data[$co_ta-1];
  }else{
    $host = $data[$co_ta-3].'.'.$data[$co_ta-2].'.'.$data[$co_ta-1];
  }
  return $host;
}
$api = 
[
    [
        'name' => 'IP查询接口',
        'cname' => 'ip',
        'info' => 'IPv4查询接口',
        'url' => '/api/v2/ip/ip/8.8.8.8',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '手机号接口',
        'cname' => 'mobile',
        'info' => '手机号查询接口',
        'url' => '/api/v2/mobile/mobile/18888888888',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '身份证查询接口',
        'cname' => 'idcard',
        'info' => '身份证信息查询接口',
        'url' => '/api/v2/idcard/idcard/430426200210242123',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'whois接口',
        'cname' => 'whois',
        'info' => 'whois查询接口',
        'url' => '/api/v2/whois/domain/www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'NS查询接口',
        'cname' => 'whois',
        'info' => 'NS服务器查询接口',
        'url' => '/api/v2/whois/domain/www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '汉字转拼音',
        'cname' => 'pinyin',
        'info' => '汉字转拼音接口',
        'url' => '/api/v2/pinyin/?text=梦城',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '短链接生成',
        'cname' => 'url',
        'info' => 't.cn&url.cn短链生成',
        'url' => '/api/v2/url/site/t.cn/?url=https://www.gqink.cn/',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '二维码生成',
        'cname' => 'QrCode',
        'info' => '在线二维码生成接口',
        'url' => '/api/v2/QrCode/?text=https://www.gqink.cn/',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '二维码解析',
        'cname' => 'QrReader',
        'info' => '在线二维码解析接口',
        'url' => '/api/v2/QrReader/?url=https://api.gqink.cn/api/v2/QrCode/?text=https://www.gqink.cn/',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'MD5加密接口',
        'cname' => 'MD5',
        'info' => '在线MD5加密接口',
        'url' => '/api/v2/MD5/?text=梦城',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'ICP查询接口',
        'cname' => 'icp',
        'info' => '在线查询域名备案接口',
        'url' => '/api/v2/icp/domain/www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机网易热评',
        'cname' => 'netease',
        'info' => '随机返回一条网易热评',
        'url' => '/api/v2/netease/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机网名接口',
        'cname' => 'name',
        'info' => '随机返回一条网名数据',
        'url' => '/api/v2/name/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机签名接口',
        'cname' => 'autograph',
        'info' => '随机返回一条签名',
        'url' => '/api/v2/autograph/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机说说接口',
        'cname' => 'shuoshuo',
        'info' => '随机返回一条说说',
        'url' => '/api/v2/shuoshuo/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机一言接口',
        'cname' => 'word',
        'info' => '随机返回一句话接口',
        'url' => '/api/v2/word/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机暖心情话',
        'cname' => 'love',
        'info' => '随机返回一句情话',
        'url' => '/api/v2/love/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'Bing每日图',
        'cname' => 'bing_img',
        'info' => '随机返回Bing每日新图',
        'url' => '/api/v2/bing_img/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机动漫图',
        'cname' => 'dm_img',
        'info' => '随机返回动漫图',
        'url' => '/api/v2/dm_img/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '语言翻译接口',
        'cname' => 'fanyi',
        'info' => '在线语言翻译接口',
        'url' => '/api/v2/fanyi/lang/AUTO/?text=梦城',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'PING接口',
        'cname' => 'ping',
        'info' => 'PING延时检测接口',
        'url' => '/api/v2/ping/ip/www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '机器人接口',
        'cname' => 'robot',
        'info' => '在线机器人接口',
        'url' => '/api/v2/robot/?text=梦城',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '天气查询接口',
        'cname' => 'weather',
        'info' => '即时更新天气接口',
        'url' => '/api/v2/weather/location/长沙市',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '垃圾分类接口',
        'cname' => 'laji',
        'info' => '在线AI垃圾分类接口',
        'url' => '/api/v2/laji/kw/香蕉皮',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '搜索收录量查询',
        'cname' => 'check',
        'info' => '查询百度搜狗360收录条数',
        'url' => '/api/v2/check/domain/www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '域名查询接口',
        'cname' => 'check_domain',
        'info' => '查询域名是否被注册接口',
        'url' => '/api/v2/check_domain/domain/gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '域名报红查询',
        'cname' => 'Url_sec',
        'info' => '查询域名是否在QQ微信报红',
        'url' => '/api/v2/Url_sec/?url=https://www.gqink.cn',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '百度图床接口',
        'cname' => 'Baidu_Upload',
        'info' => '百度图床图片上传接口',
        'url' => '/api/v2/Baidu_Upload/',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '搜狗图床接口',
        'cname' => 'Sogou_Upload',
        'info' => '搜狗图床图片上传接口',
        'url' => '/api/v2/Sogou_Upload/',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => 'IP签名图',
        'cname' => 'ip_img',
        'info' => 'IP签名图接口',
        'url' => '/api/v2/ip_img/',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '随机代理IP',
        'cname' => 'proxy',
        'info' => '随机返回一个代理IP',
        'url' => '/api/v2/proxy/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机头像接口',
        'cname' => 'headimg',
        'info' => '随机返回一张头像图片',
        'url' => '/api/v2/headimg/kw/动漫头像',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '历史上的今天',
        'cname' => 'today',
        'info' => '今天发生在历史的那些事！',
        'url' => '/api/v2/today/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '文字转语音合成',
        'cname' => 'audio',
        'info' => '文字转语音合成接口',
        'url' => '/api/v2/audio/?text=梦城',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '随机颜色代码',
        'cname' => 'colors',
        'info' => '随机颜色代码接口',
        'url' => '/api/v2/colors/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'QQ群头像',
        'cname' => 'qunlogo',
        'info' => 'Q群头像接口',
        'url' => '/api/v2/qunlogo/qun/934647025',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => '成语接龙',
        'cname' => 'chengyu',
        'info' => '成语接龙接口',
        'url' => '/api/v2/chengyu/text/望梅止渴',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机笑话',
        'cname' => 'xiaohua',
        'info' => '随机笑话接口',
        'url' => '/api/v2/xiaohua/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'HTTP状态码获取',
        'cname' => 'HttpCode',
        'info' => '获取HTTP状态码接口',
        'url' => '/api/v2/HttpCode/?url=https://www.gqink.cn/',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机密码生成',
        'cname' => 'RandPass',
        'info' => '随机密码生成接口',
        'url' => '/api/v2/RandPass/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '客户端信息',
        'cname' => 'UserInfo',
        'info' => '客户端访问信息',
        'url' => '/api/v2/UserInfo/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '网页提示跳转',
        'cname' => 'Go',
        'info' => '跳转提示功能页面',
        'url' => '/api/v2/Go/?url=',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '网易云榜单解析',
        'cname' => 'Music_List',
        'info' => '网易云音乐榜单解析',
        'url' => '/api/v2/Music_list_163/id/3778678',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '网易音乐解析',
        'cname' => 'music_163',
        'info' => '网易云音乐解析接口',
        'url' => '/api/v2/music_163/id/1398663411',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '酷狗音乐解析',
        'cname' => 'Kugou',
        'info' => '酷狗音乐解析接口',
        'url' => '/api/v2/Kugou/id/7927879CA5664B8E7B90E3688EE2AA29',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'QQ音乐解析',
        'cname' => 'qq',
        'info' => '酷狗音乐解析接口',
        'url' => '/api/v2/qq/id/001U2GJO2hSzQW',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '酷我音乐解析',
        'cname' => 'kuwo',
        'info' => '酷我音乐解析接口',
        'url' => '/api/v2/kuwo/id/80155748',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '虾米音乐解析',
        'cname' => 'xiami',
        'info' => '虾米音乐解析接口',
        'url' => '/api/v2/xiami/id/1816062575',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '咪咕音乐解析',
        'cname' => 'migu',
        'info' => '咪咕音乐解析接口',
        'url' => '/api/v2/migu/id/63898400181',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '音乐链接解析',
        'cname' => 'MusicUrl',
        'info' => '全网音乐链接解析接口',
        'url' => '/api/v2/MusicUrl/?url=http://y.qq.com/n/yqq/song/003UAhhG2Bm3Nq.html',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '音乐搜索接口',
        'cname' => 'music',
        'info' => '全网音乐搜索接口',
        'url' => '/api/v2/music/input/冬眠/site/netease/page/1',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '行政区域查询',
        'cname' => 'Music_List',
        'info' => '行政区域查询接口',
        'url' => '/api/v2/district/keyword/长沙',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '实时天气数据',
        'cname' => 'WeatherInfo',
        'info' => '实时天气数据接口',
        'url' => '/api/v2/WeatherInfo/keyword/长沙',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'IP获取定位',
        'cname' => 'IpSadd',
        'info' => 'IP获取定位接口',
        'url' => '/api/v2/IpSadd/ip/222.222.222.222',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'QQ强制会话',
        'cname' => 'IpSadd',
        'info' => 'PC版QQ强制打开聊天会话',
        'url' => '/api/v2/QQChat/qq/76613040',
        'code' => 1,
        'public' => 0,
    ],
    [
        'name' => 'QQ用户信息',
        'cname' => 'QQInfo',
        'info' => '获取qq昵称头像接口',
        'url' => '/api/v2/QQInfo/qq/76613040',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '抖音无水印解析',
        'cname' => 'douyin',
        'info' => '抖音视频无水印在线解析',
        'url' => '/api/v2/douyin/?url=https://v.douyin.com/7CMnV6/',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '全民k歌解析',
        'cname' => 'kg',
        'info' => '全民K歌在线解析',
        'url' => '/api/v2/kg/id/ihbTajiPBBOr8iCI',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'QQ凶吉查询',
        'cname' => 'qqxj',
        'info' => 'QQ号凶吉查询接口',
        'url' => '/api/v2/qqxj/qq/76613040',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '手机凶吉查询',
        'cname' => 'telxj',
        'info' => '手机号凶吉查询接口',
        'url' => '/api/v2/telxj/tel/18888888888',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '随机舔狗日记',
        'cname' => 'dog',
        'info' => '随机返回一条舔狗日记',
        'url' => '/api/v2/dog/type/json',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '微视无水印解析',
        'cname' => 'weishi',
        'info' => '微视无水印解析接口',
        'url' => '/api/v2/weishi?url=https://h5.weishi.qq.com/weishi/feed/6Z9SiVCMd1JcMkCNQ/wsfeed?wxplay=1&id=6Z9SiVCMd1JcMkCNQ&spid=1518934357272279&qua=v1_and_weishi_6.6.5_588_312026001_d&chid=100081014&pkg=3670&attach=cp_reserves3_1000370011',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '皮皮虾视频解析',
        'cname' => 'pipixia',
        'info' => '皮皮虾无水印解析',
        'url' => '/api/v2/pipixia/?url=https://h5.pipix.com/s/7ccyUx/',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '秒拍无水印解析',
        'cname' => 'pipixia',
        'info' => '秒拍视频无水印解析',
        'url' => '/api/v2/miaopai?url=http://www.miaopai.com/show/Qo3uI72UKWF-EriUFLL~VA__.htm',
        'code' => 1,
        'public' => 1,
    ],
];
$tool = [
    [ 
        'name' => '搜音乐',
        'url' => 'https://www.'.get_host().'/music.html',
        'ico' => 'fa fa-music',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '服务器状态',
        'url' => 'https://www.'.get_host().'/state.html',
        'ico' => 'fa fa-server',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'IP查询',
        'url' => 'https://www.'.get_host().'/ip.html',
        'ico' => 'fa fa-map-marker',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '手机号查询',
        'url' => 'https://www.'.get_host().'/mobile.html',
        'ico' => 'fa fa-mobile',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '身份证查询',
        'url' => 'https://www.'.get_host().'/idcard.html',
        'ico' => 'fa fa-id-card',
        'target' => '',
        'code' => 1,
    ],
    [
        'name' => 'whois查询',
        'url' => 'https://www.'.get_host().'/whois.html',
        'ico' => 'fa fa-wikipedia-w',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'NS记录查询',
        'url' => 'https://www.'.get_host().'/dns.html',
        'ico' => 'fa fa-internet-explorer',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '汉字转拼音',
        'url' => 'https://www.'.get_host().'/hanzi_pinyin.html',
        'ico' => 'fa fa-language',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '短网址生成',
        'url' => 'https://www.'.get_host().'/url.html',
        'ico' => 'fa fa-link',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '二维码生成',
        'url' => 'https://www.'.get_host().'/QrCode.html',
        'ico' => 'fa fa-qrcode',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '扫码提取SKEY',
        'url' => 'https://www.'.get_host().'/skey.html',
        'ico' => 'fa fa-qq',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '获取百度BDUSS',
        'url' => 'https://api.'.get_host().'/api/v2/Go/?url=https://api.'.get_host().'/tool/BDUSS/',
        'ico' => 'fa fa-paw',
        'target' => '_blank',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '域名转发',
        'url' => 'https://api.'.get_host().'/api/v2/Go/?url=https://url.'.get_host().'/user/',
        'ico' => 'fa fa-external-link-square',
        'target' => '_blank',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '音游Mikutap',
        'url' => 'https://api.'.get_host().'/api/v2/Go/?url=https://api.'.get_host().'/tool/mikutap/',
        'ico' => 'fa fa-gamepad',
        'target' => '_blank',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'MD5加密',
        'url' => 'https://www.'.get_host().'/MD5.html',
        'ico' => 'fa fa-unlock-alt',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '在线识别二维码',
        'url' => 'https://www.'.get_host().'/QrReader.html',
        'ico' => 'fa fa-qrcode',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'ICP备案查询',
        'url' => 'https://www.'.get_host().'/icp.html',
        'ico' => 'fa fa-info',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '在线翻译',
        'url' => 'https://www.'.get_host().'/fanyi.html',
        'ico' => 'fa fa-language',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'BASE64加密解密',
        'url' => 'https://www.'.get_host().'/base64.html',
        'ico' => 'fa fa-code',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'URL编码转换',
        'url' => 'https://www.'.get_host().'/UrlCode.html',
        'ico' => 'fa fa-link',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'PING延时测试',
        'url' => 'https://www.'.get_host().'/ping.html',
        'ico' => 'fa fa-clock-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '机器人',
        'url' => 'https://www.'.get_host().'/robot.html',
        'ico' => 'fa fa-android',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '在线垃圾分类',
        'url' => 'https://www.'.get_host().'/laji.html',
        'ico' => 'fa fa-trash',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '天气查询',
        'url' => 'https://www.'.get_host().'/weather.html',
        'ico' => 'fa fa-sun-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '搜索收录量查询',
        'url' => 'https://www.'.get_host().'/check.html',
        'ico' => 'fa fa-check-circle-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '域名注册查询',
        'url' => 'https://www.'.get_host().'/domain.html',
        'ico' => 'fa fa-globe',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '域名报红检测',
        'url' => 'https://www.'.get_host().'/Url_Sec.html',
        'ico' => 'fa fa-link',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '图床图片上传',
        'url' => 'https://www.'.get_host().'/Img_Upload.html',
        'ico' => 'fa fa-file-image-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '文件大小转换',
        'url' => 'https://www.'.get_host().'/filesize.html',
        'ico' => 'fa fa-building-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'JS/HTML格式化',
        'url' => 'https://www.'.get_host().'/jshtml_format.html',
        'ico' => 'fa fa-code',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'XML/压缩格式化',
        'url' => 'https://www.'.get_host().'/xmlsort.html',
        'ico' => 'fa fa-file-excel-o',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'CSS压缩/格式化',
        'url' => 'https://www.'.get_host().'/css.html',
        'ico' => 'fa fa-css3',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => 'HTTP状态查询',
        'url' => 'https://www.'.get_host().'/HTTPCode.html',
        'ico' => 'fa fa-internet-explorer',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '设置拒绝添加',
        'url' => 'https://www.'.get_host().'/authf.html',
        'ico' => 'fa fa-fire',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '单项好友检测',
        'url' => 'https://www.'.get_host().'/danxiang.html',
        'ico' => 'fa fa-list-ol',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '在线清空资料',
        'url' => 'https://www.'.get_host().'/qqinfo.html',
        'ico' => 'fa fa-info',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '设置空白昵称',
        'url' => 'https://www.'.get_host().'/qqnick.html',
        'ico' => 'fa fa-crosshairs',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '抖音无水印解析',
        'url' => 'https://www.'.get_host().'/douyin.html',
        'ico' => 'fa fa-video-camera',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
    [
        'name' => '微视无水印解析',
        'url' => 'https://www.'.get_host().'/weishi.html',
        'ico' => 'fa fa-video-camera',
        'target' => '',
        'code' => 1,
        'public' => 1,
    ],
];
$nav = 
[
    [
        'name' => '负载状态',
        'url' => 'https://www.'.get_host().'/state.html',
        'ico' => 'fa fa-server',
    ],
    [
        'name' => '工具列表',
        'url' => 'https://www.'.get_host().'/tool.html',
        'ico' => 'fa fa-toggle-on',
    ],
    [
        'name' => '免费接口',
        'url' => 'https://www.'.get_host().'/api.html',
        'ico' => 'fa fa-database',
    ],
    [
        'name' => '接口日志',
        'url' => 'https://www.'.get_host().'/log.html',
        'ico' => 'fa fa-clock-o',
    ],
];
$headimg = 
[
    [
        'name' => '女生头像',
        'url' => 'https://www.'.get_host().'/nvsheng.html',
    ],
    [
        'name' => '男生头像',
        'url' => 'https://www.'.get_host().'/nansheng.html',
    ],
    [
        'name' => '动漫头像',
        'url' => 'https://www.'.get_host().'/dongman.html',
    ],
    [
        'name' => '动漫男头',
        'url' => 'https://www.'.get_host().'/dongmannan.html',
    ],
    [
        'name' => '动漫女头',
        'url' => 'https://www.'.get_host().'/dongmannv.html',
    ],
    [
        'name' => '文字头像',
        'url' => 'https://www.'.get_host().'/wenzitou.html',
    ],
    [
        'name' => '欧美头像',
        'url' => 'https://www.'.get_host().'/oumei.html',
    ],
    [
        'name' => '玩网女头',
        'url' => 'https://www.'.get_host().'/wanwangnvtou.html',
    ],
    [
        'name' => '情侣头像',
        'url' => 'https://www.'.get_host().'/qinglutou.html',
    ],
    [
        'name' => '表情图片',
        'url' => 'https://www.'.get_host().'/biaoqing.html',
    ],
];
$word = 
[
    [
        'name' => '网易热评',
        'url' => 'https://www.'.get_host().'/netease.html',
    ],
    [
        'name' => '暖心情话',
        'url' => 'https://www.'.get_host().'/love.html',
    ],
    [
        'name' => '精选网名',
        'url' => 'https://www.'.get_host().'/name.html',
    ],
    [
        'name' => '精选签名',
        'url' => 'https://www.'.get_host().'/autograph.html',
    ],
    [
        'name' => '精选说说',
        'url' => 'https://www.'.get_host().'/shuoshuo.html',
    ],
    [
        'name' => '精选一言',
        'url' => 'https://www.'.get_host().'/word.html',
    ],
];
json([
    'By'=>'与梦城',
    'url'=>'https://www.'.get_host(),
    'api'=>$api,
    'tool'=>$tool,
    'nav'=>$nav,
    'headimg' => $headimg,
    'word' => $word,
]);
?>